export { TerrainScene } from './components/TerrainScene'
export { SceneCameraControls } from './components/SceneCameraControls'
export { initialPerfStats } from './types'
export { SCENE_CAMERA } from './config'
export type { HeightmapPreviewData, PerfStats, WaterRenderConfig } from './types'
