import type { GeneratorControlValues, TerrainPresetName } from '../types'

export const TERRAIN_PRESET_OPTIONS: TerrainPresetName[] = [
  'Custom',
  'Archipelago',
  'AlpineRidges',
  'SoftDunes',
  'VolcanicPlateau',
  'CanyonMaze',
  'FrozenHighlands',
  'CoastalShelf',
  'CraterField',
  'RollingHills',
  'JungleCraters',
  'RiverValley',
  'GlacialValley',
  'SandstoneArches',
  'HighlandSteppe',
  'AtollChain',
  'StormCliffs',
  'LavaDelta',
  'MistyIslands',
  'TectonicSpine',
]

export const TERRAIN_PRESET_DESCRIPTIONS: Record<TerrainPresetName, string> = {
  Custom: 'Mode libre. Les modifications manuelles detachees restent en Custom.',
  Archipelago: 'Iles fragmentees avec relief modere et transitions douces.',
  AlpineRidges: 'Cretes marquees et hauts reliefs alpins.',
  SoftDunes: 'Grandes dunes lissees en niveaux de gris.',
  VolcanicPlateau: 'Plateaux rugueux et zones craterisees.',
  CanyonMaze: 'Ravinements profonds facon labyrinthes de canyons.',
  FrozenHighlands: 'Massifs froids et sommets etires.',
  CoastalShelf: 'Plateformes littorales et pentes progressives vers l ocean.',
  CraterField: 'Surface parsemee de cuvettes et d impacts.',
  RollingHills: 'Collines douces et regulieres.',
  JungleCraters: 'Relief tropical nerveux avec de larges depressions.',
  RiverValley: 'Vallees ouvertes et couloirs naturels de drainage.',
  GlacialValley: 'Vallees glaciaires et cretes adoucies.',
  SandstoneArches: 'Badlands tabulaires et strates abruptes.',
  HighlandSteppe: 'Hautes plaines ventees et relief peu fracture.',
  AtollChain: 'Chapelet d atolls bas et lagons peu profonds.',
  StormCliffs: 'Falaises agressives et fronts cotiers escarpes.',
  LavaDelta: 'Epanchements basaltiques en eventail et ruptures seches.',
  MistyIslands: 'Archipel humide aux reliefs arrondis.',
  TectonicSpine: 'Epine dorsale montagneuse tres contrast ee.',
}

export const TERRAIN_PRESETS: Record<
  Exclude<TerrainPresetName, 'Custom'>,
  Partial<GeneratorControlValues>
> = {
  Archipelago: {
    seed: 'archipelago-v2',
    heightmap: 'PerlinDiamond',
    smoothing: 'Gaussian (1.0, 7)',
    scattering: 'PerlinAltitude',
    curve: 'EaseInOut',
    texture: 'Blended',
    amplitude: 22,
    frequency: 0.016,
    octaves: 5,
    persistence: 0.52,
    lacunarity: 2.1,
    viewRadius: 2,
  },
  AlpineRidges: {
    seed: 'alpine-v2',
    heightmap: 'SimplexLayers',
    smoothing: 'Conservative (1)',
    scattering: 'Worley',
    curve: 'EaseIn',
    texture: 'Blended',
    amplitude: 40,
    frequency: 0.01,
    octaves: 6,
    persistence: 0.46,
    lacunarity: 2.25,
    viewRadius: 2,
  },
  SoftDunes: {
    seed: 'dunes-v2',
    heightmap: 'Value',
    smoothing: 'GaussianBox',
    scattering: 'Linear',
    curve: 'EaseOut',
    texture: 'Grayscale',
    amplitude: 14,
    frequency: 0.02,
    octaves: 4,
    persistence: 0.58,
    lacunarity: 1.8,
    viewRadius: 3,
  },
  VolcanicPlateau: {
    seed: 'volcano-v2',
    heightmap: 'Worley',
    smoothing: 'Median',
    scattering: 'Worley',
    curve: 'EaseOut',
    texture: 'Blended',
    amplitude: 34,
    frequency: 0.013,
    octaves: 5,
    persistence: 0.49,
    lacunarity: 2.35,
    viewRadius: 2,
  },
  CanyonMaze: {
    seed: 'canyon-v1',
    heightmap: 'Fault',
    smoothing: 'Conservative (0.5)',
    scattering: 'Perlin',
    curve: 'EaseOut',
    texture: 'Blended',
    amplitude: 46,
    frequency: 0.009,
    octaves: 4,
    persistence: 0.42,
    lacunarity: 2.6,
    viewRadius: 2,
  },
  FrozenHighlands: {
    seed: 'frozen-highlands-v1',
    heightmap: 'SimplexLayers',
    smoothing: 'Gaussian (1.0, 11)',
    scattering: 'Altitude',
    curve: 'EaseIn',
    texture: 'Blended',
    amplitude: 52,
    frequency: 0.008,
    octaves: 6,
    persistence: 0.44,
    lacunarity: 2.3,
    viewRadius: 2,
  },
  CoastalShelf: {
    seed: 'coastal-shelf-v1',
    heightmap: 'PerlinLayers',
    smoothing: 'Gaussian (1.0, 7)',
    scattering: 'PerlinAltitude',
    curve: 'EaseInOut',
    texture: 'Blended',
    amplitude: 18,
    frequency: 0.014,
    octaves: 5,
    persistence: 0.55,
    lacunarity: 2.05,
    viewRadius: 3,
  },
  CraterField: {
    seed: 'crater-field-v1',
    heightmap: 'Worley',
    smoothing: 'Median',
    scattering: 'Particles',
    curve: 'EaseOut',
    texture: 'Grayscale',
    amplitude: 28,
    frequency: 0.021,
    octaves: 4,
    persistence: 0.5,
    lacunarity: 2.4,
    viewRadius: 2,
  },
  RollingHills: {
    seed: 'rolling-hills-v1',
    heightmap: 'Value',
    smoothing: 'GaussianBox',
    scattering: 'Linear',
    curve: 'EaseInOut',
    texture: 'Blended',
    amplitude: 12,
    frequency: 0.018,
    octaves: 4,
    persistence: 0.62,
    lacunarity: 1.7,
    viewRadius: 3,
  },
  JungleCraters: {
    seed: 'jungle-craters-v1',
    heightmap: 'PerlinLayers',
    smoothing: 'Gaussian (1.0, 7)',
    scattering: 'Particles',
    curve: 'EaseInOut',
    texture: 'Blended',
    amplitude: 30,
    frequency: 0.017,
    octaves: 6,
    persistence: 0.53,
    lacunarity: 2.2,
    viewRadius: 2,
  },
  RiverValley: {
    seed: 'river-valley-v1',
    heightmap: 'PerlinDiamond',
    smoothing: 'Conservative (1)',
    scattering: 'Altitude',
    curve: 'Linear',
    texture: 'Blended',
    amplitude: 24,
    frequency: 0.011,
    octaves: 5,
    persistence: 0.5,
    lacunarity: 2,
    viewRadius: 3,
  },
  GlacialValley: {
    seed: 'glacial-valley-v1',
    heightmap: 'SimplexLayers',
    smoothing: 'Gaussian (1.5, 7)',
    scattering: 'Worley',
    curve: 'EaseIn',
    texture: 'Blended',
    amplitude: 44,
    frequency: 0.007,
    octaves: 6,
    persistence: 0.43,
    lacunarity: 2.35,
    viewRadius: 2,
  },
  SandstoneArches: {
    seed: 'sandstone-arches-v1',
    heightmap: 'Fault',
    smoothing: 'Conservative (10)',
    scattering: 'CosineLayers',
    curve: 'EaseOut',
    texture: 'Blended',
    amplitude: 38,
    frequency: 0.01,
    octaves: 4,
    persistence: 0.4,
    lacunarity: 2.7,
    viewRadius: 2,
  },
  HighlandSteppe: {
    seed: 'highland-steppe-v1',
    heightmap: 'Brownian',
    smoothing: 'Mean (1)',
    scattering: 'Linear',
    curve: 'EaseInOut',
    texture: 'Grayscale',
    amplitude: 20,
    frequency: 0.013,
    octaves: 5,
    persistence: 0.57,
    lacunarity: 1.9,
    viewRadius: 3,
  },
  AtollChain: {
    seed: 'atoll-chain-v1',
    heightmap: 'Worley',
    smoothing: 'Gaussian (1.0, 5)',
    scattering: 'PerlinAltitude',
    curve: 'EaseInOut',
    texture: 'Blended',
    amplitude: 16,
    frequency: 0.022,
    octaves: 4,
    persistence: 0.6,
    lacunarity: 1.8,
    viewRadius: 4,
  },
  StormCliffs: {
    seed: 'storm-cliffs-v1',
    heightmap: 'DiamondSquare',
    smoothing: 'Conservative (1)',
    scattering: 'Perlin',
    curve: 'EaseOut',
    texture: 'Blended',
    amplitude: 58,
    frequency: 0.006,
    octaves: 7,
    persistence: 0.41,
    lacunarity: 2.45,
    viewRadius: 2,
  },
  LavaDelta: {
    seed: 'lava-delta-v1',
    heightmap: 'Worley',
    smoothing: 'Median',
    scattering: 'Worley',
    curve: 'EaseOut',
    texture: 'Grayscale',
    amplitude: 32,
    frequency: 0.016,
    octaves: 5,
    persistence: 0.48,
    lacunarity: 2.5,
    viewRadius: 2,
  },
  MistyIslands: {
    seed: 'misty-islands-v1',
    heightmap: 'Perlin',
    smoothing: 'GaussianBox',
    scattering: 'Cosine',
    curve: 'EaseInOut',
    texture: 'Blended',
    amplitude: 21,
    frequency: 0.015,
    octaves: 5,
    persistence: 0.56,
    lacunarity: 2.05,
    viewRadius: 3,
  },
  TectonicSpine: {
    seed: 'tectonic-spine-v1',
    heightmap: 'Weierstrass',
    smoothing: 'Conservative (0.5)',
    scattering: 'PerlinAltitude',
    curve: 'EaseIn',
    texture: 'Blended',
    amplitude: 64,
    frequency: 0.005,
    octaves: 7,
    persistence: 0.39,
    lacunarity: 2.8,
    viewRadius: 2,
  },
}
